//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПР6_часть_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int ID { get; set; }
        public string Loginn { get; set; }
        public string Passwordd { get; set; }
        public string Rolee { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
    }
}
